[package]
name = "hyprhito"
version = "0.1.0"
edition = "2021"
description = "Low-level laptop lid display manager"
authors = ["hito"]

[dependencies]
tokio = { version = "1.0", features = ["full"] }
log = "0.4"
env_logger = "0.10"
evdev = "0.12"
